# Generated by Django 3.1.3 on 2021-07-19 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorize_users', '0002_authorizeuser_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authorizeuser',
            name='username',
            field=models.EmailField(max_length=250, unique=True),
        ),
    ]
