# Generated by Django 3.1.3 on 2021-07-28 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorize_users', '0005_auto_20210719_0215'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorizeuser',
            name='is_complete_approval',
            field=models.BooleanField(default=False),
        ),
    ]
