# Generated by Django 3.1.3 on 2021-07-28 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorize_users', '0006_authorizeuser_is_complete_approval'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorizeuser',
            name='valid_id',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='valid_ids'),
        ),
    ]
