# Generated by Django 3.1.3 on 2021-07-30 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorize_users', '0012_announcements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcements',
            name='announcement',
            field=models.TextField(default='Bayanihan News'),
        ),
    ]
